# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_document_by_lda_cpp <- function(length, topic_probs, topic_type_probs) {
    .Call('_docsler_sample_document_by_lda_cpp', PACKAGE = 'docsler', length, topic_probs, topic_type_probs)
}

sample_corpus_by_lda_cpp <- function(length, topic_probs, topic_type_probs) {
    .Call('_docsler_sample_corpus_by_lda_cpp', PACKAGE = 'docsler', length, topic_probs, topic_type_probs)
}

